---
- name: Update yum
  shell: yum update -y
  become: true

- name: Install Java and NFS utils
  yum: 
    name: java-11-openjdk,java-11-openjdk-devel, nfs-utils
    state: present
  become: true

- name: Export environment variables
  shell: | 
    sudo tee /etc/profile.d/java11.sh <<EOF 
    export JAVA_HOME=\$(dirname \$(dirname \$(readlink \$(readlink \$(which javac)))))
    export PATH=\$PATH:\$JAVA_HOME/bin export CLASSPATH=.:\$JAVA_HOME/jre/lib:\$JAVA_HOME/lib:\$JAVA_HOME/lib/tools.jar 
    export AA="TES123fdT"
    EOF
   
123
- name: Set environment varaibles
  shell: source /etc/profile.d/java11.sh
  args:
    executable: /bin/bash

- name: Validate that "wheel" group exists
  group:
    name: wheel
    state: present

- name: Create pcadmin user
  user:
    name: pcadmin
    state: present
    groups: "wheel"
    append: yes
    createhome: yes
    password: "123123"
  become: true
    

- name: Check if ActiveMQ archive is already present
  stat:
    path: apache-activemq-5.17.4
  register: activemq_archive

- name: Create data directory
  file:
    path: /data/bus/trigger
    state: directory
    mode: '0755'
    owner: pcadmin
    group: pcadmin
  become: true

- name: Create target directory
  file:
    path: /local/java/activemq
    state: directory
    mode: '0755'
    owner: pcadmin
    group: pcadmin
  become: true


- name: Retrieve ActiveMQ and unpack it
  shell: |
    wget https://downloads.apache.org/activemq/5.17.4/apache-activemq-5.17.4-bin.tar.gz
    tar xvf apache-activemq-5.17.4-bin.tar.gz
    mv apache-activemq-5.17.4 /local/java/activemq/
    chown -R pcadmin:pcadmin /local/java/activemq/apache-activemq-5.17.4
  become: true
  when: activemq_archive.stat.exists == False

- name: Link directories
  file: 
    src: /local/java/activemq/apache-activemq-5.17.4
    dest: /local/java/activemq/current
    state: link
    owner: pcadmin
    group: pcadmin
  become: true 
    
- name: Create local directory
  file:
    path: /local/scripts
    mode: '0755'
    state: directory
    owner: pcadmin
    group: pcadmin
  become: true

# - name: Create init module
#   copy:
#     src: active-mq/files/activemq.init.erb
#     dest: /etc/init.d/activemq
#     owner: root
#     group: root
#     mode: '0755'
#   become: true

# - name: Create init module locally
#   copy:
#     src: active-mq/files/activemq.init.erb
#     dest: /local/scripts/activemq
#     mode: '0755'
#     owner: pcadmin
#     group: pcadmin
#   become: true


# - name: Create ActiveMQ util script
#   copy:
#     src: active-mq/files/activemqutil.sh.erb
#     dest: /local/scripts/activemqutil.sh
#     mode: '0755'
#     owner: pcadmin
#     group: pcadmin
#   become: true

# - name: Create AMQ admin binary
#   copy:
#     src: active-mq/files/activemq-admin.init
#     dest: /local/java/activemq/current/bin/activemq-admin
#     mode: '0755'
#     owner: pcadmin
#     group: pcadmin
#   become: true

- name: Create jetty.xml
  copy:
    src: active-mq/files/jetty.xml
    dest: /local/java/activemq/current/conf/jetty.xml
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true


- name: Create log directory 1
  file:
    path: /var/log/activemq
    owner: pcadmin
    group: pcadmin
    mode: '0755'
    state: directory
  become: true

- name: Create log directory 2
  file:
    path: /local/logs/activemq
    owner: pcadmin
    group: pcadmin
    mode: '0755'
    state: directory
  become: true

- name: Create log file
  file:
    state: touch
    path: /var/log/activemq/activemq.log
    owner: pcadmin
    group: pcadmin
    mode: '0644'
  become: true

- name: Create styles file
  copy:
    src: active-mq/files/site.css.activemq.erb
    dest: /local/java/activemq/current/webapps/admin/styles/site.css
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true
  

- name: Create logging properties file
  copy:
    src: active-mq/files/log4j.properties.activemq.erb
    dest: /local/java/activemq/current/conf/log4j.properties
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true

- name: Create jetty-realm file
  copy:
    src: active-mq/files/jetty-realm.properties.activemq
    dest: /local/java/activemq/current/conf/jetty-realm.properties
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true
 
- name: Create activemq.xml
  copy: 
    src: active-mq/files/activemq-with-dupfilter-plugin.xml.erb
    dest: /local/java/activemq/current/conf/activemq.xml
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true
 
- name: Upload JAR for Duplicate Filter
  copy:
    src: active-mq/files/activemq-duplicates-filter-1.0.0.jar
    dest: /local/java/activemq/current/lib
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true


- name: Create Duplicate Filter Plugin
  copy: 
    src: active-mq/files/duplicate-filter-plugin.xml.activemq
    dest: /local/java/activemq/current/conf/duplicate-filter-plugin.xml
    mode: '0644'
    owner: pcadmin
    group: pcadmin
  become: true

- name: Copy systemd unit
  copy:
    src: active-mq/files/apache-activemq.service
    dest: /etc/systemd/system/apache-activemq.service
  become: true

- name: Reload daemon and modify SELinux
  shell: |
    systemctl daemon-reload
    setenforce 0
    sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
  become: true


- name: Start and enable ActiveMQ
  shell: |
    systemctl enable apache-activemq.service
    systemctl start apache-activemq.service
  become: true

- name: Create mount directory
  shell: |
    mkdir -p /share/activemq-store
  become: true

- name: Mount Azure File Share
  mount:
    path: /data/bus/trigger
    src: activemqshare.dss-test.dv.azure.private.inf0.net:/activemqdatastorage/activemqdb
    fstype: nfs
    opts: vers=4,minorversion=1,sec=sys
    state: mounted
  become: true


- name: Restart ActiveMQ to enable Active-Passive mode
  shell: systemctl restart apache-activemq.service
  become: true

