# We need branch protection rule for all below to have purpose

env:
  SEARCH_PATTERN: "[_AUTO_] - pull-request"
  MASTER_BRANCH_NAME: "main"
  STAGING_BRANCH_NAME: "staging"

permissions:
  pull-requests: write
  contents: write

name: "Merge to master"
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  auto_merge_master:
    name: "Merge to master automatically"
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and filter pull requests
        id: fetch-prs
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequests = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            const invalidMasterPrs = pullRequests.filter(pr =>
                pr.base.ref === '${{ env.MASTER_BRANCH_NAME }}' && !pr.title.includes('${{ env.SEARCH_PATTERN }}'));
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `pulls=${JSON.stringify(pullRequests.data)}\n`);
            console.log("Status code for GET pull requests: " + pullRequests.status)

  # - name: "Send Slack notification (success)"
  #   id: send-fail-message
  #   uses: rtCamp/action-slack-notify@v2
  #   env:
  #     SLACK_CHANNEL: "test_interaction_channel2"
  #     SLACK_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  #     SLACK_MESSAGE: "Test have failed"
  #     SLACK_COLOR: "success"
  #     SLACK_USERNAME: "borg-sphere"
  #     SLACK_ICON: "https://avatars.slack-edge.com/2020-05-22/1133584994822_7ae043ae65db02608c79_512.jpg"
