# We need branch protection rule for all below to have purpose

env:
  SEARCH_PATTERN: "[_AUTO_] - pull-request"
  MASTER_BRANCH_NAME: "main"
  STAGING_BRANCH_NAME: "staging"

permissions:
  pull-requests: write

name: "Merge to master"
on:
  push:
    branches:
      - staging
  schedule:
    - cron: "*/5 * * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  auto_merge_master:
    name: "Do an auto-merge to master"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Fetch and filter pull requests
        id: fetch-prs
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequests = ( await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
            })).data.filter(pr => pr.base.ref === '${{ env.MASTER_BRANCH_NAME }}' && pr.title.includes('${{ env.SEARCH_PATTERN }}'))
            const existingMasterPrs = ${{ steps.fetch-prs.outputs.pulls }}.filter(pr =>
              pr.base.ref === '${{ env.MASTER_BRANCH_NAME }}' && pr.title.includes('${{ env.SEARCH_PATTERN }}'))

            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `existingMasterPrs=${JSON.stringify(existingMasterPrs)}\n`);
            console.log("Status code for GET pull requests: " + pullRequests.status)
            console.log(pullRequests);

      # - name:

      # - name: Process valid pull request to master
      #   id: process-valid-master-prs
      #   if: ${{ needs.fetch-prs.outputs.validMasterPrs != '[]' }}
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const prs = ${{ needs.fetch-prs.outputs.validMasterPrs }}
      #       prs.forEach(pr => {
      #         github.rest.pulls.merge({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           pull_number: pr.number,
      #           }).then(response => {
      #             if (response.status === 200) {
      #               console.log(`Pull request ${pr.title}/${pr.number} to branch ${{ env.MASTER_BRANCH_NAME }} has been successfuly merged! Status code: ${response.status}`);
      #             } else {
      #               console.log(`Couldn't merge ${pr.title}/${pr.number}. Status code: ${response.status}`);
      #             }
      #             }).catch(error => {
      #               console.error(`Failed to close PR ${pr.title}/${pr.number}: `, error.message);
      #           });
      #         });

  close_invalid_prs:
    name: "Close PRs created to master by humans"
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Fetch and close manual PRs to master if any
        id: fetch-and-close-invalid-prs
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequests = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
            });

            const invalidMasterPrs = pullRequests.filter(pr =>
                pr.base.ref === '${{ env.MASTER_BRANCH_NAME }}' && !pr.title.includes('${{ env.SEARCH_PATTERN }}'));

            if (invalidMasterPrs.length > 0) {
              console.log("Close PR")
            }

      - name: Fetch and filter pull requests
        id: send-slack-message
        uses: actions/github-script@v6
        with:
          script: |
            console.log('${{ steps.fetch-and-close-invalid-prs.conclusion }}')
            console.log('${{ steps.fetch-and-close-invalid-prs.outcome }}')

        #2DO
      #Send slack message if process-valid-master-prs failed
      #Send slack message if process-valid-master-prs succeeded
      #Send slack message if process-invalid-master-prs was not skipped and PR was closed successfuly
      #Send slack message if process-invalid-master-prs was not skipped but PR was not closed successfuly
