# ST_NAME
# CLOSED_PULL_REQUESTS (list)
# NEW_PULL_REQUESTS (list)
# FAILED_TEST_LST (list)
# AUTO_PR_LST (list)
# SECOND_MSG (bool)
# CUSTOM_STAGE (string)

# We set initial value to string for empty lists because there is no list data structure in GitHub Actions
env:
  closed_pull_requests: ""
  new_pull_requests: "[]"
  failed_test_lst: ""
  auto_pr_lst: ""
  second_msg: ${{ false }}
  custom_stage: ""
  github_base_url: "https://github.com"
  github_api_url: "https://api.github.com/repos/gdcorp-engineering/migration-tech-framework"
  slack_channel: "borg_github_internal"
  slack_token_id: "slack_borg_github_internal"
  SEARCH_PATTERN: "[_AUTO_] - pull-request"
  MASTER_BRANCH_NAME: "master"
  STAGING_BRANCH_NAME: "staging"

#TODO retention settings as in  Jenkins buildDiscarder

# Timestamps are supported in logs with shift + T
# Xterm highlighting is supported by default
# SkipDefaultCheckout is the default behavior

# 5 minutes is the shortest schedule GitHub can do
# [push] is for tests
name: "Ansible Lint"
on:
  [push]
  #schedule:
  #  - cron: "*/5 * * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  get_pull_requests:
    name: Search for open pull requests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch all pull requests
        id: fetch-prs
        uses: actions/github-script@v6
        with:
          script: |
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, 'FAIL_RES=Get pull requests');
            const response = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const pullRequests = JSON.stringify(response.data);
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `pulls=${pullRequests}\n`);
            console.log("Status code for GET pull requests: " + response.status)

      - name: Search for automatic pull requests
        id: process-prs
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ steps.fetch-prs.outputs.pulls }})
            const pullRequests = JSON.parse(process.env.PULLS);
            const newPullRequests = pullRequests.filter(pr =>
              pr.base.ref === ${{ env.MASTER_BRANCH_NAME }} && pr.title.includes(${{ env.SEARCH_PATTERN }}));
            console.log('Filtered pull requests: ', newPullRequests)
        env:
          PULLS: ${{ steps.fetch-prs.outputs.pulls }}
