# ST_NAME
# CLOSED_PULL_REQUESTS (list)
# NEW_PULL_REQUESTS (list)
# FAILED_TEST_LST (list)
# AUTO_PR_LST (list)
# SECOND_MSG (bool)
# CUSTOM_STAGE (string)

# We set initial value to string for empty lists because there is no list data structure in GitHub Actions
env:
  closed_pull_requests: ""
  new_pull_requests: "[]"
  failed_test_lst: ""
  auto_pr_lst: ""
  second_msg: ${{ false }}
  custom_stage: ""
  github_base_url: "https://github.com"
  github_api_url: "https://api.github.com/repos/gdcorp-engineering/migration-tech-framework"
  slack_channel: "borg_github_internal"
  slack_token_id: "slack_borg_github_internal"
  SEARCH_PATTERN: "[_AUTO_] - pull-request"
  MASTER_BRANCH_NAME: "main"
  STAGING_BRANCH_NAME: "staging"

#TODO retention settings as in  Jenkins buildDiscarder

# Timestamps are supported in logs with shift + T
# Xterm highlighting is supported by default
# SkipDefaultCheckout is the default behavior

# 5 minutes is the shortest schedule GitHub can do
# [push] is for tests
name: "Ansible Lint"
on:
  [push]
  #schedule:
  #  - cron: "*/5 * * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  get_pull_requests:
    name: Search for open pull requests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch all pull requests
        id: fetch-prs
        uses: actions/github-script@v6
        with:
          script: |
            const valid_prs = [];
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, 'FAIL_RES=Get pull requests\n');
            const pullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `pulls=${JSON.stringify(pullRequests)}\n`);
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `valid_prs=${valid_prs}\n`);
            console.log("Status code for GET pull requests: " + pullRequests.status)

      - name: Search for invalid pull requests to master
        id: process-invalid-prs
        if: steps.fetch-prs.outputs.pulls != ''
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Dummy for now')

      - name: Search for auto pull requests to master
        id: process-auto-prs
        if: steps.fetch-prs.outputs.pulls != ''
        uses: actions/github-script@v6
        with:
          script: |
            const masterPullRequests = ${{ steps.fetch-prs.outputs.pulls }}.filter(pr =>
              pr.base.ref === '${{ env.MASTER_BRANCH_NAME }}' && pr.title.includes('${{ env.SEARCH_PATTERN }}'));
            const valid_prs = ${{ steps.fetch-prs.outputs.valid_prs }}
            valid_prs.push(...masterPullRequests)
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `valid_prs=${JSON.stringify(valid_prs)}\n`);
            console.log('Filtered pull requests to master: ', masterPullRequests);

      - name: Search for valid pull requests to staging
        id: process-staging-prs
        if: steps.fetch-prs.outputs.pulls != ''
        uses: actions/github-script@v6
        with:
          script: |
            const stagingPullRequests = ${{ steps.fetch-prs.outputs.pulls }}.filter(pr =>
              pr.base.ref === '${{ env.MASTER_BRANCH_NAME }}' && pr.title.includes('fix'));
            const valid_prs = ${{ steps.process-auto-prs.outputs.valid_prs }};
            valid_prs.push(...stagingPullRequests);
            console.log(valid_prs)

#newPullRequests.push(...additionalPullRequest);
