# We need branch protection rule for all below to have purpose

permissions:
  pull-requests: write

name: "Ansible Lint"
on:
  pull_request_target:
    branches:
      - staging
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_ansible_lint:
    name: "Run ansible-lint"
    runs-on: ubuntu-latest

    steps:
      - name: "Get list of changed files"
        id: get-changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const filesFullList = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.number }}
            });
            const filesNames = filesFullList.data.map(file => file.filename).join(' ');
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `filesNames=${JSON.stringify(filesNames)}\n`);
            console.log(filesNames)

      - name: "Checkout source branch"
        id: checkout-scm
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Otherwise linter accept list of files as a single string filename
      - name: "Remove trailing and leading quotes"
        id: format-filenames
        run: |
          FILENAMES=${{ steps.get-changed-files.outputs.filesNames }}
          FILENAMES="${FILENAMES%\"}"
          FILENAMES="${FILENAMES#\"}"
          echo "FILENAMES=$FILENAMES" >> $GITHUB_ENV

      - name: "Run ansible-lint"
        id: run-lint
        uses: ansible/ansible-lint@main
        with:
          args: ${{ env.FILENAMES }}

      # Add SLACK_API_TOKEN in Github secrets
      - name: "Send Slack notification (fail)"
        id: send-fail-message
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "dteran-test"
          SLACK_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_MESSAGE: "Test have failed"
          SLACK_COLOR: "failure"
          SLACK_USERNAME: "borg-sphere"
          SLACK_ICON: "https://avatars.slack-edge.com/2020-05-22/1133584994822_7ae043ae65db02608c79_512.jpg"

      # Uncomment if logic is desired
      # - name: "Close pull request if tests failed"
      #   id: close-failed-pr
      #   if: failure()
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       await github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: ${{ github.event.number }},
      #         body: "Pull Request has been closed because it didn't pass tests"
      #       });

      #       await github.rest.pulls.update({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: ${{ github.event.number }},
      #         state: "closed"
      #       });

      # 'Allow GitHub Actions to create and approve pull requests' has to be enabled in repository Settings > Actions > General (most bottom line)
